version: '3.4'

services:
  bluestar-nuxt:
    image: bluestar-nuxt
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js